baseURL = "https://fixmy-internet.netlify.app/"
title = "Fix My Internet"
theme = "PaperMod"
locale = "en-US"
enableRobotsTXT = true
paginate = 20

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
mainSections = ["internet"]

[menu]
  [[menu.main]]
    name = "Internet"
    url = "/internet/"
    weight = 1

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
